Task oop 4 module 8
StellaVS/Java_base_stalina pull request #10
Opened 2016-12-04 12:29 UTC by StellaVS

Создать свой собственный класс строки, базирующийся на массиве символов. Реализовать для него простейшие операции: создание, возврат длины, сложение строк, далее на ваш выбор

2016-12-08 17:39 UTC, strazhkoe requested changes
Why do we have 2 ImplementString classes?

2016-12-08 17:39 UTC, strazhkoe commented on src/dp/ort/ua/task_OOP_03_module_8/ImplementString.java
> +		symbols = symbol;
we need to copy this array here

2016-12-08 17:39 UTC, strazhkoe commented on src/dp/ort/ua/task_OOP_03_module_8/ImplementString.java
> +	public void appendChar(char userSymbols) {
Why is argument called userSymbols? We pass only one char here. Please, rename.

2016-12-08 17:39 UTC, strazhkoe commented on src/dp/ort/ua/task_OOP_03_module_8/ImplementString.java
> +		return symbols;
We should return a copy here.

2016-12-14 19:54 UTC, StellaVS commented on src/dp/ort/ua/task_OOP_03_module_8/ImplementString.java
> +	public void appendChar(char userSymbols) {
argument renamed userSymbol

2016-12-18 11:43 UTC, strazhkoe approved these changes

2016-12-18 11:43 UTC, merged