Task oop inharitance.foreign passport 10
StellaVS/Java_base_stalina pull request #13
Opened 2017-01-12 11:27 UTC by StellaVS

10. Создайте класс Passport, который будет содержать паспортные данные гражданина Украины. С помощью наследования (расширения), создайте класс ForeignPassport (паспорт для выезда за границу) производный от Passport. Загранпаспорт содержит данные о визах и номер загранпаспорта. Визу рекомендую реализовать как отдельный класс и типом визы и датой открытия и закрытия (плюс дополнительные свойства на ваше усмотрение)

2017-01-22 09:18 UTC, strazhkoe requested changes

2017-01-22 09:18 UTC, strazhkoe commented on src/ort/dp/ua/task_OOP_Inheritance/ForeignPassport_10/ForeignPassport.java
> +			System.err.printf("У гражданина %s %s " + "нет места для визы %n", getFirstName(), getLastName());
Этот метод лучше сделать, возвращающим boolean, а сообщение выводить в интерфейсе

2017-01-22 09:18 UTC, strazhkoe commented on src/ort/dp/ua/task_OOP_Inheritance/ForeignPassport_10/UkrainePassport.java
> +	}
Используй get и set методы

2017-01-22 09:18 UTC, strazhkoe commented on src/ort/dp/ua/task_OOP_Inheritance/ForeignPassport_10/Visa.java
> +	private String _typeVisa;
слово Visa в имени поля лишнее, ведь это поле находится в классе Visa. Других типов тут нет

2017-01-24 19:57 UTC, StellaVS commented on src/ort/dp/ua/task_OOP_Inheritance/ForeignPassport_10/Visa.java
> +	private String _typeVisa;
поле переименовано

2017-01-24 19:57 UTC, StellaVS commented on src/ort/dp/ua/task_OOP_Inheritance/ForeignPassport_10/UkrainePassport.java
> +	}
Методы использованы:
`{
setTypeVisa(type);
		setDateOpen(dateOpen);
		setDateClose(dateClose);
}`

2017-02-03 10:44 UTC, strazhkoe requested changes

2017-02-03 10:44 UTC, strazhkoe commented on src/ort/dp/ua/task_OOP_Inheritance/ForeignPassport_10/Visa.java
> +	private String _dateOpen;
вместо типа String для даты нужно использовать Calendar, или хотя бы long

2017-02-16 19:33 UTC, StellaVS commented on src/ort/dp/ua/task_OOP_Inheritance/ForeignPassport_10/Visa.java
> +	private String _dateOpen;
Use class Calendar

2017-02-21 17:47 UTC, strazhkoe approved these changes

2017-02-21 17:47 UTC, merged