Delete from String "Privet"
StellaVS/Java_base_stalina pull request #5
Opened 2016-11-16 21:05 UTC by StellaVS

// 9.167. Дано предложение. Напечатать все его слова, отличные от слова привет.

2016-11-20 10:23 UTC, strazhkoe requested changes

2016-11-20 10:23 UTC, strazhkoe commented on src/ua/dp/ort/chapter9/task_9_167.java
> +		StringBuffer strigOfWords = new StringBuffer("Как много в этом слове Привет.И добродушие,и свет.");
Вместо StringBuffer используй StringBuilder. StringBuffer используется при совместном доступе к нему из нескольких потоков, но он из-за этого медленнее работает.

2016-11-23 20:09 UTC, StellaVS commented
Using StringBuilder

2016-11-27 08:14 UTC, strazhkoe approved these changes

2016-11-27 08:14 UTC, merged