Task №1 OOP create an array of points and are sorted by the distance
StellaVS/Java_base_stalina pull request #7
Opened 2016-11-20 12:49 UTC by StellaVS

* 1.Дан массив точек. Каждая точка характеризуется координатами х, у и
 * названием точки. Сортировать точки в массиве по возрастанию удаления
 * расстояния точки от начала координат и вывести их на экран

2016-11-20 13:04 UTC, strazhkoe commented on src/task_OOP_01_module_8/ArrayPoints.java
> +		Point[] point = new Point[4];
что означают имена переменных g и f?

2016-11-20 13:05 UTC, strazhkoe requested changes
В целом ок

2016-11-20 13:05 UTC, strazhkoe commented on src/task_OOP_01_module_8/Point.java
> +	}
Тут лучше имени присвоить какое-то дефолтное название

2016-11-23 20:03 UTC, StellaVS commented
1. Rename variables

2. Awarded the default point name

2016-11-26 20:57 UTC, strazhkoe approved these changes

2016-11-26 20:57 UTC, merged